version: "3.7"

services:

    rabbitMQ:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq

        ports:
            - 5672:5672
            - 15692:15692
            - 15672:15672

    mongodb:
        image: mongo:4.0.20
        expose:
          - "27017"
        ports:
          - "27018:27017"

    # mongo-seed:
    #     build:
    #       context: database-seed
    #       dockerfile: Dockerfile
    #     depends_on:
    #       - mongodb


    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: backend
        restart: on-failure
        ports:
          - "8080:5000"
        volumes:
          - ./backend:/home/app
        depends_on:
          - rabbitMQ
          - mongodb
